config/routes.rb
Cbx::Application.routes.draw do
  resources :bars

  get "home/index"

root :to => 'home#index'

end

app/models/bar.rb
class Bar < ActiveRecord::Base
  #attr_accessible :imagepath
  mount_uploader :imagepath, BarlogoUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/bars_controller.rb
class BarsController < ApplicationController
  
  http_basic_authenticate_with:name => "cbx",    :password => "philly123"
  
  # GET /bars
  # GET /bars.json
  def index
    @bars = Bar.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @bars }
    end
  end

  # GET /bars/1
  # GET /bars/1.json
  def show
    @bar = Bar.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @bar }
    end
  end

  # GET /bars/new
  # GET /bars/new.json
  def new
    @bar = Bar.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @bar }
    end
  end

  # GET /bars/1/edit
  def edit
    @bar = Bar.find(params[:id])
  end

  # POST /bars
  # POST /bars.json
  def create
    @bar = Bar.new(params[:bar])

    respond_to do |format|
      if @bar.save
        format.html { redirect_to @bar, :notice => 'Bar was successfully created.' }
        format.json { render :json => @bar, :status => :created, :location => @bar }
      else
        format.html { render :action => "new" }
        format.json { render :json => @bar.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /bars/1
  # PUT /bars/1.json
  def update
    @bar = Bar.find(params[:id])

    respond_to do |format|
      if @bar.update_attributes(params[:bar])
        format.html { redirect_to @bar, :notice => 'Bar was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @bar.errors, :status => :unprocessable_entity }
      end
    end
  end
  


  # DELETE /bars/1
  # DELETE /bars/1.json
  def destroy
    @bar = Bar.find(params[:id])
    @bar.destroy

    respond_to do |format|
      format.html { redirect_to bars_url }
      format.json { head :ok }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  # GET /bars
  # GET /bars.json
  def index
    @bars = Bar.all(:order => 'displayorder') 

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @bars }
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bars_helper.rb
module BarsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/bars/_form.html.erb
<%= form_for(@bar) do |f| %>
  <% if @bar.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bar.errors.count, "error") %> prohibited this bar from being saved:</h2>

      <ul>
      <% @bar.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :address1 %><br />
    <%= f.text_field :address1 %>
  </div>
  <div class="field">
    <%= f.label :address2 %><br />
    <%= f.text_field :address2 %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :eventname %><br />
    <%= f.text_field :eventname %>
  </div>
  <div class="field">
    <%= f.label :eventdesc %><br />
    <%= f.text_area :eventdesc %>
  </div>
  <div class="field">
    <%= f.label :imagepath %><br />
    <%= f.file_field :imagepath %>
  </div>
  <div class="field">
    <%= f.label :ticketurl %><br />
    <%= f.text_field :ticketurl %>
  </div>
  <div class="field">
    <%= f.label :TapFinderURL %><br />
    <%= f.text_field :TapFinderURL %>
  </div>
  <div class="field">
    <%= f.label :displayorder %><br />
    <%= f.text_field :displayorder %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bars/edit.html.erb
<section id="edit" class="admin">

	<h1>Editing bar</h1>

	<%= render 'form' %>

	<%= link_to 'Show', @bar %> |
	<%= link_to 'Back', bars_path %>
</section>

app/views/bars/index.html.erb
<section id="index" class="admin">
	<h1>All Bars</h1>

	<table cellpadding="5" cellspacing="5">

		<% @bars.each do |bar| %>
		<tr>
			<td width="400"><%= bar.name %></td>
			<td><%= link_to 'Show', bar %></td>
			<td><%= link_to 'Edit', edit_bar_path(bar) %></td>
			<td><%= link_to 'Destroy', bar, :confirm => 'Are you sure?', :method => :delete %></td>
		</tr>
		<% end %>
	</table>

	<br />

	<%= link_to 'New Bar', new_bar_path %>
</section>

app/views/bars/new.html.erb
<section id="new" class="admin">
	<h1>New bar</h1>

	<%= render 'form' %>

	<%= link_to 'Back', bars_path %>
</section>

app/views/bars/show.html.erb
<section id="show" class="admin">
		<p id="notice"><%= notice %></p>

		<p>
			<b>Name:</b>
			<%= @bar.name %>
		</p>

		<p>
			<b>Phone:</b>
			<%= @bar.phone %>
		</p>

		<p>
			<b>Address1:</b>
			<%= @bar.address1 %>
		</p>

		<p>
			<b>Address2:</b>
			<%= @bar.address2 %>
		</p>

		<p>
			<b>Url:</b>
			<%= @bar.url %>
		</p>

		<p>
			<b>Eventname:</b>
			<%= @bar.eventname %>
		</p>

		<p>
			<b>Eventdesc:</b>
			<%= @bar.eventdesc %>
		</p>

		<p>
			<b>Imagepath:</b>
			<%= @bar.imagepath %>
		</p>


		<%= link_to 'Edit', edit_bar_path(@bar) %> |
		<%= link_to 'Back', bars_path %>
	</section>

app/views/home/index.html.erb
<header id="top">
	<img src="/img/cbx_logo.png" alt="Craft Beer Express" id="cbx_logo" />
</header>



<!-- Countdown dashboard start -->
<div id="countdown_dashboard1">

	<div class="dash days_dash">

		<div class="digit">0</div>
		<div class="digit">1</div>

	</div>

	<div class="dash hours_dash">

		<div class="digit">1</div>
		<div class="digit">0</div>

	</div>

	<div class="dash minutes_dash">

		<div class="digit">0</div>
		<div class="digit">5</div>

	</div>

	<div class="dash seconds_dash">

		<div class="digit">5</div>
		<div class="digit">4</div>

	</div>

</div>
<!-- Countdown dashboard end -->



<div class="section_top"></div>
<section id="home">
	<img class="header_img" src="/img/header_home.png" alt="All Aboard the Express!"/>
	<div style="height: 15px">&nbsp;</div>
	<div class="left">
		<p class="body_copy"> 
			The concept behind the Craft Beer Express is simple. A handful of Philly bar owners wanted to share their love of beer with people
			who appreciate a fine brew as much as they do. What better way than a pub
			crawl? We collaborated to create a crawl that would attract a knowledgeable
			audience who has a passion for quality beers and in-depth tasting events.
			<em>Just like that, the CBX was born.</em> While we'd love to have as large a
			crowd as possible at our bars, we’d also like to make sure everyone is
			comfortable &ndash; <strong>so ticket sales are limited.</strong> We
			constantly add buses to the route to minimize wait times and to maximize
			adequate seating. The CBX grows every year (two events per year), so gather
			your friends and enjoy the finest beers Philly has to offer. Tickets are
			available online up until the day of the event.
		</p>
	</div>
	<div class="right">
		<br/>
		<img src="/img/cbx_date.png" class="cbx_date" />
	</div>
	<div class="clear"></div>
</section>
<div class="clear"></div>

<div class="section_bottom"></div>

<a name="bars"></a>
<div class="section_top"></div>
<section id="bars">
	<img class="header_img" src="/img/header_bars.png" alt="Participating Bars &amp; Tickets" />

	<span class="orange">
		Bus tickets are $10 each plus a small processing fee or you can avoid the fee by visiting any of the participating bars to purchase tickets.  You may start at any bar you wish - just click BUY TICKETS next to that corresponding bar’s logo below and it will take you to its ticket link. Upon choosing a starting location you will need to start at that bar on the day of the event. There will you will be able to exchange your paper ticket for your wrist bracelet so that you may ride the bus.  If you have purchased a paper ticket from any of the bars you can use that ticket to start at any location you want.  All sales are final so please be sure that the bar you choose is the one you wish to start at.
	</span>

</section>
<div class="section_bottom_bars"></div>

<% @bars.each do |bar| %>
<div class="bar <% if bar == @bars.last %>last<% end %>">
	<div class="bar_left">
		<table>
			<tr>
				<td valign="top" width="140">
					<img class="barimg" src="<%= bar.imagepath %>" alt="<%= bar.name %>" height="122" width="130" />
				</td>
				<td valign="top" width="300">
					<span class="bar-name"><%= bar.name %></span>
					<br/>
					<%= bar.address1 %>
					<br/>
					<%= bar.phone %>
					<br/>
					<a href="<%= bar.url %>" target="_blank">Visit Site</a>
					<br/>
					<% if !bar.TapFinderURL.blank? then %>
					<br/>
					<a href="<%= bar.TapFinderURL %>" target="_blank"><img valign="bottom" align="left" src="/img/tapfinder_btn.png" alt="Philly Tap Finder"/></a>
					<% else %>
					<br/>
					<% end %>
					<a href="<%= bar.ticketurl %>"><img valign="bottom" align="right" src="/img/buytix.png" alt="Buy Tickets"/></a>
				</td>
			</tr>
		</table>
	</div>
	<div class="bar_right">	
		<span class="bardesc_name"><strong><%= bar.eventname %></strong></span>
		<%= raw bar.eventdesc %>
	</div>
</div>
	<% end %>


	<a name="map"></a>
	<div class="section_top"></div>
	<section id="map">

		<img class="header_img" src="/img/header_map.png" alt="Map &amp; Location of CBX Stops" />
		<div class="left">
			<p class="body_copy">
				The CBX is on Saturday, March 9, 2013 from 11am to 
				 and will have a series of buses running loops between the following bars (Kraftwork, Johnny Brenda's, The Institute, Bishop's Collar, Kite &amp; Key, Jose Pistolas, Sidecar, P.O.P.E, Devil's Den, Brauhaus Schmitz &amp; Race St. Cafe). The cost of the bus tickets are $10 and can be purchased above online, or in-person at any of the participating bars. The busses will run approximately every 25 minutes.
			</p>

			<div id="bar_list">
				<table>
					<tr>
						<!-- STANDARD TAP COMMENTED OUT -->
						<!--<td width="250px">
							<table>
								<tr><td class="bar_letter">A</td><td class="bar_name">Kraftwork</td></tr>
								<tr><td class="bar_letter">B</td><td class="bar_name">Johnny Brenda's</td></tr>
								<tr><td class="bar_letter">C</td><td class="bar_name">Standard Tap</td></tr>
								<tr><td class="bar_letter">D</td><td class="bar_name">Institute</td></tr>
								<tr><td class="bar_letter">E</td><td class="bar_name">Bishop's Collar</td></tr>
								<tr><td class="bar_letter">F</td><td class="bar_name">Kite &amp; Key</td></tr>
							</table>
						</td>
							<td width="250px">
								<table>
									<tr><td class="bar_letter">G</td><td class="bar_name">Jose Pistolas</td></tr>
									<tr><td class="bar_letter">H</td><td class="bar_name">Sidecar</td></tr>
									<tr><td class="bar_letter">I</td><td class="bar_name">P.O.P.E.</td></tr>
									<tr><td class="bar_letter">J</td><td class="bar_name">Devil's Den</td></tr>
									<tr><td class="bar_letter">K</td><td class="bar_name">Brauhaus Schmitz</td></tr>
									<tr><td class="bar_letter">L</td><td class="bar_name">Race St. Cafe</td></tr>
								</table>
							</td>-->

							<td width="250px" valign="top">
							<table>
								<tr><td class="bar_letter">A</td><td class="bar_name">Kraftwork</td></tr>
								<tr><td class="bar_letter">B</td><td class="bar_name">Johnny Brenda's</td></tr>
								<tr><td class="bar_letter">C</td><td class="bar_name">The Institute</td></tr>
								<tr><td class="bar_letter">D</td><td class="bar_name">Bishop's Collar</td></tr>
								<tr><td class="bar_letter">E</td><td class="bar_name">Kite &amp; Key</td></tr>
								<tr><td class="bar_letter">F</td><td class="bar_name">Jose Pistolas</td></tr>
							</table>
						</td>
							<td width="250px"  valign="top">
								<table>
									<tr><td class="bar_letter">G</td><td class="bar_name">Sidecar</td></tr>
									<tr><td class="bar_letter">H</td><td class="bar_name">P.O.P.E.</td></tr>
									<tr><td class="bar_letter">I</td><td class="bar_name">Devil's Den</td></tr>
									<tr><td class="bar_letter">J</td><td class="bar_name">Brauhaus Schmitz</td></tr>
									<tr><td class="bar_letter">K</td><td class="bar_name">Race St. Cafe</td></tr>
								</table>
							</td>
						</tr>
						</table>
					</div>

				</div>
				<div class="right">
					<div style="height:13px">&nbsp;</div>
					<!-- STANDARD TAP COMMENTED OUT -->
					<!--<iframe width="425" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="http://maps.google.com/maps?f=d&amp;source=s_d&amp;saddr=Kraftwork,+East+Girard+Avenue,+Philadelphia,+PA&amp;daddr=Johnny+Brendas,+Frankford+Avenue,+Philadelphia,+PA+to:Standard+Tap,+Philadelphia,+PA+to:549+North+12th+Street,+Philadelphia,+PA+19123-3332+(The+Institute)+to:Bishops+Collar,+Fairmount+Avenue,+Philadelphia,+PA+to:Kite+%26+Key+Tavern,+Callowhill+Street,+Philadelphia,+PA+to:Jose+Pistolas+Restaurant,+South+15th+Street,+Philadelphia,+PA+to:Sidecar+Bar+and+Grille,+Christian+Street,+Philadelphia,+PA+to:1501+East+Passyunk+Avenue,+Philadelphia,+PA+19147-6322+(Pub+On+Passyunk+East)+to:Devils+Den,+South+11th+Street,+Philadelphia,+PA+to:Brauhaus+Schmitz,+South+Street,+Philadelphia,+PA+to:Race+Street+Cafe,+Race+Street,+Philadelphia,+PA&amp;hl=en&amp;geocode=Fb3qYQIdyaWF-yFFiy_KbvizbQ%3BFSPhYQId-4qF-yES0n_mNPsDlA%3BFevNYQIdBnKF-yHmEuP0WSatrg%3BFeHIYQIdvzCF-yHnNxhwzstW5SmJHoXS1cfGiTG4A4Sjo8LVCw%3BFVPbYQIdauSE-yHf336pgLbIIQ%3BFZO_YQIdhQCF-yGMInRr6Hk7WQ%3BFZCNYQIdLQ6F-yF-5sZei7F3EQ%3BFcN2YQIdKNqE-ylDgc0iQMbGiTFjGAfzu43nfA%3BFeNLYQIdAR6F-yFIoTnoaN7tIA%3BFUNfYQIdMB6F-yGhomrJVaH-Hykl2tkZGcbGiTFIK_XtgIPd_A%3BFVl4YQIdWzuF-yG17p0PgSoD-A%3BFYClYQIdbmeF-yE0Sh00v5SB2g&amp;sll=39.958044,-75.159187&amp;sspn=0.074343,0.143337&amp;vpsrc=0&amp;mra=ltm&amp;ie=UTF8&amp;ll=39.958044,-75.159187&amp;spn=0.04118,0.05238&amp;t=m&amp;output=embed"></iframe>-->
					<iframe width="425" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com/maps?f=d&amp;source=s_d&amp;saddr=Kraftwork,+541+E+Girard+Ave,+Philadelphia,+PA&amp;daddr=Johnny+Brenda's,+Frankford+Avenue,+Philadelphia,+PA+to:The+Institute+Bar,+549+N+12th+St,+Philadelphia,+PA+to:Bishop's+Collar,+2349+Fairmount+Ave,+Philadelphia,+PA+to:Kite+%26+Key,+Callowhill+Street,+Philadelphia,+PA+to:Jose+Pistola's,+South+15th+Street,+Philadelphia,+PA+to:The+Sidecar+Bar+%26+Grille,+Christian+Street,+Philadelphia,+PA+to:The+Pub+on+Passyunk+East,+East+Passyunk+Avenue,+Philadelphia,+PA+to:Devil's+Den,+South+11th+Street,+Philadelphia,+PA+to:Brauhaus+Schmitz,+South+Street,+Philadelphia,+PA+to:Race+Street+Cafe,+Race+Street,+Philadelphia,+PA&amp;hl=en&amp;geocode=Fb3qYQIdyaWF-yFFiy_KbvizbSllaGIaQcjGiTFFiy_KbvizbQ%3BFSzhYQId9oqF-yES0n_mNPsDlClL3KCNe8bGiTES0n_mNPsDlA%3BFezIYQIdZTCF-yFzMUsj8pdpcSmJHoXS1cfGiTFzMUsj8pdpcQ%3BFfPaYQIdaOSE-yHf336pgLbIISkH2cjDycfGiTHf336pgLbIIQ%3BFZO_YQIdhQCF-yF8aoXlzA0ksSmxZZ3RzMfGiTF8aoXlzA0ksQ%3BFbyNYQIdbQ2F-yF-5sZei7F3ESlJE1vNOsbGiTF-5sZei7F3EQ%3BFcJ2YQId-dmE-yFjGAfzu43nfClDgc0iQMbGiTFjGAfzu43nfA%3BFeNLYQIdAR6F-yFIoTnoaN7tICn7rZ0NG8bGiTFIoTnoaN7tIA%3BFUNfYQIdMB6F-yGhomrJVaH-Hykl2tkZGcbGiTGhomrJVaH-Hw%3BFYJ4YQIdZDuF-yG17p0PgSoD-Cl1pJunIMbGiTG17p0PgSoD-A%3BFVylYQIdZmeF-yE0Sh00v5SB2iknuRgshsjGiTE0Sh00v5SB2g&amp;aq=0&amp;oq=Johnny+Brenda'&amp;sll=39.950806,-75.153351&amp;sspn=0.074483,0.151577&amp;mra=ls&amp;ie=UTF8&amp;t=m&amp;z=13&amp;output=embed"></iframe>


				</div>
				<div class="clear"></div>
		
			</section>
			<div class="section_bottom"></div>
			<a name="contact"></a>
			<div class="section_top"></div>
			<section id="contact">
				<img class="header_img" src="/img/header_news.png" alt="Stay on Track with the CBX!" />
				<div class="left">
					<img src="/img/cbx_date.png" class="cbx_date" />

					<div class="blue_bg">
						<p class="larger">Keep checking our website for details, and stay in the know by following the CBX on Facebook and Twitter. <br/><strong>See you on the Express!</strong></p>
						<p>Have a specific question? <a href="mailto:charlie@institutebar.com">Email us</a></p>
					</div>


					<table width="480">
						<tr>
							<td>
								<img src="/img/facebook.png" alt="" />
							</td>
							<td>		<!-- Countdown dashboard start -->
								<div id="countdown_dashboard2">

									<div class="dash days_dash">

										<div class="digit">0</div>
										<div class="digit">1</div>

									</div>

									<div class="dash hours_dash">

										<div class="digit">1</div>
										<div class="digit">0</div>

									</div>

									<div class="dash minutes_dash">

										<div class="digit">0</div>
										<div class="digit">5</div>

									</div>

									<div class="dash seconds_dash">

										<div class="digit">5</div>
										<div class="digit">4</div>

									</div>

								</div>
								<!-- Countdown dashboard end -->
							</td>
							<td><img src="/img/twitter.png" alt="" />
							</td>
						</tr>
					</table>
					<br/>

					<a href="http://www.phillytapfinder.com"><img src="/img/PTF_logo.png" alt="Philly Tap Finder"></a>
				</div>
				<div class="right" style="text-align: right; padding-right:10px; width: 450px">
					<!--<div id="fb-root" style="text-align:right"></div>
					<script>(function(d, s, id) {
						var js, fjs = d.getElementsByTagName(s)[0];
						if (d.getElementById(id)) {return;}
						js = d.createElement(s); js.id = id;
						js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
						fjs.parentNode.insertBefore(js, fjs);
						}(document, 'script', 'facebook-jssdk'));</script>-->

						<div class="fb-like-box" data-href="http://www.facebook.com/pages/Craft-Beer-Express/154719327880220" data-width="430" data-height="640" data-show-faces="true" data-stream="true" data-header="true">

					</div>
				</div>
				<div class="clear"></div>
			</section>
			<div class="section_bottom"></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Craft Beer Express</title>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.6.4/jquery.js"></script>

	<%= stylesheet_link_tag    "application" %>
	<%= javascript_include_tag "application" %>
	<%= csrf_meta_tags %>
	<script src="/js/functions.js"></script>
	<script src="/js/modernizr-1.7.min.js"></script>
	<script src="/js/jquery.scrollTo.js"></script>
	<script src="/js/jquery.nav.min.js"></script>
	<script src="/js/jquery.lwtCountdown-1.0.js"></script>
	<link type="text/css" href="/css/normalize.css" rel="Stylesheet" />
	<link type="text/css" href="/css/cbx.css" rel="Stylesheet" />

	<script type="text/javascript"	src="http://maps.googleapis.com/maps/api/js?sensor=false"></script>

	<meta property="og:title" content="Craft Beer Express" />
	<meta property="og:type" content="website" />
	<meta property="og:image" content="http://www.craftbeerexpress.com/img/cbx_logo.png" />
	<meta property="og:url" content="http://www.craftbeerexpress.com/" />
	<meta property="og:site_name" content="Craft Beer Express" />
	<meta property="fb:app_id" content="154719327880220" />

</head>
<body>
	<nav>
		<ul>
			<li><a href="#top"><img src="/img/nav_home.png" alt="Home" /></a></li>
			<li><a href="#bars"><img src="/img/nav_part.png" alt="Participating Bars &amp; Tickets" /></a></li>
			<li><a href="#map"><img src="/img/nav_map.png" alt="Map" /></a></li>
			<li><a href="#contact"><img src="/img/nav_contact.png" alt="Contact" /></a></li>
		</ul>
		<div id="fb_ribbon">
			<div id="fb-root"></div>
			<script>(function(d, s, id) {
				var js, fjs = d.getElementsByTagName(s)[0];
				if (d.getElementById(id)) {return;}
				js = d.createElement(s); js.id = id;
				js.src = "//connect.facebook.net/en_US/all.js#appId=120702788026282&xfbml=1";
				fjs.parentNode.insertBefore(js, fjs);
				}(document, 'script', 'facebook-jssdk'));</script>

				<div class="fb-like" data-href="http://www.facebook.com/pages/Craft-Beer-Express/154719327880220" data-send="false" data-layout="button_count"  data-show-faces="false" data-font="arial"></div>
			</div>
		</nav>
		<div id="container">
			<a name="top"></a>
			<%= yield %>
		</div>
	</body>
	</html>